Collections:
  - Name: YOLOv6
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Nesterov
        - Weight Decay
        - AMP
        - Synchronize BN
      Training Resources: 8x A100 GPUs
      Architecture:
        - CSPDarkNet
        - PAFPN
        - RepVGG
    Paper:
      URL: https://arxiv.org/abs/2209.02976
      Title: 'YOLOv6: A Single-Stage Object Detection Framework for Industrial Applications'
    README: configs/yolov6/README.md
    Code:
      URL: https://github.com/open-mmlab/mmyolo/blob/v0.0.1/mmyolo/models/detectors/yolo_detector.py#L12
      Version: v0.0.1

Models:
  - Name: yolov6_s_syncbn_fast_8xb32-400e_coco
    In Collection: YOLOv6
    Config: configs/yolov6/yolov6_s_syncbn_fast_8xb32-400e_coco.py
    Metadata:
      Training Memory (GB): 8.88
      Epochs: 400
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.0
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov6/yolov6_s_syncbn_fast_8xb32-400e_coco/yolov6_s_syncbn_fast_8xb32-400e_coco_20221102_203035-932e1d91.pth
  - Name: yolov6_n_syncbn_fast_8xb32-400e_coco
    In Collection: YOLOv6
    Config: configs/yolov6/yolov6_n_syncbn_fast_8xb32-400e_coco.py
    Metadata:
      Training Memory (GB): 6.04
      Epochs: 400
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.2
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov6/yolov6_n_syncbn_fast_8xb32-400e_coco/yolov6_n_syncbn_fast_8xb32-400e_coco_20221030_202726-d99b2e82.pth
  - Name: yolov6_t_syncbn_fast_8xb32-400e_coco
    In Collection: YOLOv6
    Config: configs/yolov6/yolov6_t_syncbn_fast_8xb32-400e_coco.py
    Metadata:
      Training Memory (GB): 8.13
      Epochs: 400
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.0
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov6/yolov6_t_syncbn_fast_8xb32-400e_coco/yolov6_t_syncbn_fast_8xb32-400e_coco_20221030_143755-cf0d278f.pth
  - Name: yolov6_m_syncbn_fast_8xb32-300e_coco
    In Collection: YOLOv6
    Config: configs/yolov6/yolov6_m_syncbn_fast_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 16.69
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 48.4
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov6/yolov6_m_syncbn_fast_8xb32-300e_coco/yolov6_m_syncbn_fast_8xb32-300e_coco_20221109_182658-85bda3f4.pth
  - Name: yolov6_l_syncbn_fast_8xb32-300e_coco
    In Collection: YOLOv6
    Config: configs/yolov6/yolov6_l_syncbn_fast_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 20.86
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.0
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov6/yolov6_l_syncbn_fast_8xb32-300e_coco/yolov6_l_syncbn_fast_8xb32-300e_coco_20221109_183156-91e3c447.pth
  - Name: yolov6_s_bn_fast_b32-120e_coco_halfperson
    In Collection: YOLOv6
    Config: configs/yolov6/yolov6_s_bn_fast_b32-120e_coco_halfperson.py
    Metadata:
      Training Memory (GB): 20.86
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.0
    Weights: /home/ubuntu/mmyolo/work_dirs/body_detect/yolov6_s_coco_halfperson/epoch_120.pth
  - Name: lad_yolov6_t_shallow_bn_fast_b32-120e_coco_halfperson_6cls
    In Collection: YOLOv6
    Config: configs/yolov6/lad_yolov6_t_shallow_bn_fast_b32-120e_coco_halfperson_6cls.py
    Metadata:
      Training Memory (GB): 20.86
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.0
    Weights: None
  - Name: yolov6_t_shallow_bn_fast_b32-120e_coco_halfperson_4cls
    In Collection: YOLOv6
    Config: configs/yolov6/yolov6_t_shallow_bn_fast_b32-120e_coco_halfperson_4cls.py
    Metadata:
      Training Memory (GB): 20.86
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.0
    Weights: None
  - Name: yolov6_t_shallow_bn_fast_b32-120e_coco_halfperson_6cls
    In Collection: YOLOv6
    Config: configs/yolov6/yolov6_t_shallow_bn_fast_b32-120e_coco_halfperson_6cls.py
    Metadata:
      Training Memory (GB): 20.86
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.0
    Weights: /home/ubuntu/mmyolo/work_dirs/body_detect/yolov6_t_shallow_s_multi_scale_rtmloss_assigner_v8_data_aug_coco_halfperson_6cls/epoch_300.pth
  - Name: yolov6_replknet_multi_scale_rtmloss_assigner_v8data_aug_6cls
    In Collection: YOLOv6
    Config: configs/yolov6/yolov6_replknet_multi_scale_rtmloss_assigner_v8data_aug_6cls.py
    Metadata:
      Training Memory (GB): 20.86
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.0
    Weights: /home/ubuntu/mmyolo/work_dirs/body_detect/yolov6_31t_shallow_replknet_multi_scale_rtmloss_assigner_v8_data_aug_coco_halfperson_6cls/epoch_120.pth
  - Name: yolov6_s_super_shallow_bn_fast_b32-120e_coco_halfperson_4cls
    In Collection: YOLOv6
    Config: configs/yolov6/yolov6_s_super_shallow_bn_fast_b32-120e_coco_halfperson_4cls.py
    Metadata:
      Training Memory (GB): 20.86
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.0
    Weights: /home/ubuntu/mmrazor/work_dirs/body_detect/cwd_yolov6_s_yolov6_s_super_shallow_coco_halfperson_4cls/epoch_120.pth